<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="ashudeep-VivoBook-ASUSLaptop-X412DA-X412DA" failures="1" tests="1" name="LoginTest" time="10.031" errors="0" timestamp="2020-11-24T14:24:35 IST">
  <testcase classname="com.pom.testcases.FlightTest" name="login" time="7.18">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [2] but found [5]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [2] but found [5]
at com.pom.testcases.FlightTest.login(FlightTest.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- login -->
</testsuite> <!-- LoginTest -->
